name: 翻译问题反馈
description: ' Create a report to help us improve '
title: "[翻译问题] 标题"
labels: [bug]
body:
- type: textarea
  id: version
  attributes:
    label: 什么地方没有翻译正确呢？
    description: >-
      简单描述下翻译问题，提供您认为正确的翻译！
    placeholder: 'Example: Application exited with code 1'
  validations:
    required: true

- type: textarea
  attributes:
    label: 截图/视频
    description: >-
      如果可以，还请带上您的截图，这会让我更快确定是哪个位置未翻译正确！
  validations:
    required: true


- type: textarea
  attributes:
    label: 其他信息
    description: |
     提供您认为翻译错误的PojavLauncher的版本信息！
       例如：
         - 是否为独立软件版本：是/否
         - PojavLauncher版本：[上一个版本]
      value: |
        - PojavLauncher version: 
    render: markdown
  validations:
    required: true
